# Generated by Django 5.2.7 on 2026-04-07 10:41

import uuid
from django.db import migrations, models

def gen_uuid(apps, schema_editor):
    Agent = apps.get_model('messaging', 'Agent')
    CannedResponse = apps.get_model('messaging', 'CannedResponse')
    Customer = apps.get_model('messaging', 'Customer')
    Message = apps.get_model('messaging', 'Message')

    for row in Agent.objects.all():
        row.external_id = uuid.uuid4()
        row.save(update_fields=['external_id'])
    
    for row in CannedResponse.objects.all():
        row.external_id = uuid.uuid4()
        row.save(update_fields=['external_id'])
        
    for row in Customer.objects.all():
        row.external_id = uuid.uuid4()
        row.save(update_fields=['external_id'])
        
    for row in Message.objects.all():
        row.external_id = uuid.uuid4()
        row.save(update_fields=['external_id'])

class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_interactionlog'),
    ]

    operations = [
        # Add the fields as nullable (no unique constraint yet)
        migrations.AddField(
            model_name='agent',
            name='external_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='cannedresponse',
            name='external_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='external_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='external_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        
        # Populate the fields with unique UUIDs
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),

        # Enforce unique=True and null=False
        migrations.AlterField(
            model_name='agent',
            name='external_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cannedresponse',
            name='external_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='external_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='external_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
