# Generated by Django 5.2.7 on 2026-04-08 11:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_agent_external_id_cannedresponse_external_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='responded_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='response',
        ),
        migrations.CreateModel(
            name='MessageReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_customer', models.BooleanField(default=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='messaging.agent')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='messaging.message')),
            ],
        ),
    ]
